[package]
name = "ArduinoGraphPlotter"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
colored = "2.2.0"
log = "0.4.22"
nannou = "0.19.0"
num-traits = "0.2.19"
once_cell = "1.20.2"
rand = "0.8.5"
serialport = "4.6.1"
